import '@/styles/global.scss'
import '@/styles/media.scss'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'aos/dist/aos.css';
import 'swiper/css';

export const metadata = {
  title: 'ZET : Become a Certified Financial Advisor and Earn Big',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
