import Banner from '@/components/home/Banner'
import Footer from '@/components/home/Footer'
import Navbar from '@/components/home/Navbar'
import Products from '@/components/home/Products'
import StartEarning from '@/components/home/StartEarning'
import TopBrands from '@/components/home/TopBrands'
import WhyUs from '@/components/home/WhyUs'
import Zeteffect from '@/components/home/Zeteffect'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>ZET : Become a Certified Financial Advisor and Earn Big</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <TopBrands />
      <Products />
      <Zeteffect />
      <WhyUs />
      <StartEarning />
      <Footer />

    </>
  )
}
